export const fleetSecretarias = [
  {
    key: 'SEME',
    nome: 'Secretaria Municipal de Educação',
    aliases: ['SEC DE EDUCACAO ENSINO FUNDAMENTAL'],
  },
  {
    key: 'ESPORTE',
    nome: 'Secretaria Municipal de Esporte e Lazer',
    aliases: ['SECRETARIA DE ESPORTE E LAZER'],
  },
  {
    key: 'PLANEJAMENTO',
    nome: 'Secretaria Municipal de Planejamento',
    aliases: ['SEC DE PLANEJAMENTO'],
  },
  { key: 'SEMAD', nome: 'Secretaria Municipal de Administração', aliases: [] },
  {
    key: 'INFRA_RURAL',
    nome: 'Secretaria Municipal de Infraestrutura Rural',
    aliases: ['SECRETARIA MUN DE INFRA ESTRUTURA RURAL'],
  },
  { key: 'SEMCULT', nome: 'Secretaria Municipal de Cultura', aliases: ['CULTURA'] },
  {
    key: 'SEMOSU',
    nome: 'Secretaria Municipal de Obras e Serviços Urbanos',
    aliases: ['SEC DE OBRAS E SERVICOS URBANOS'],
  },
  {
    key: 'SEMAS',
    nome: 'Secretaria Municipal de Assistência Social',
    aliases: ['SEMADES RECURSO PROPRIO', 'CREAS RECURSO ESTADUAL'],
  },
  { key: 'REVIVER', nome: 'Reviver', aliases: [] },
  {
    key: 'GABINETE',
    nome: 'Gabinete do Prefeito',
    aliases: ['GABINETE DO PREFEITO', 'PREFEITURA'],
  },
  {
    key: 'SEMAG',
    nome: 'Secretaria Municipal de Agricultura',
    aliases: ['SECRETARIA DE AGRICULTURA E MEIO AMBIENTE'],
  },
  { key: 'SEMLIP', nome: 'Secretaria Municipal de Limpeza Pública', aliases: [] },
] as const;

// [lotação, identificação/placa, descrição conforme FROTA MUNICIPAL 2026.pdf]
export const fleet2026 = [
  ['SEME', 'SDM5C48', 'Ônibus Mercedes-Benz OF-1519'],
  ['SEME', 'OVL0527', 'Ônibus Mercedes-Benz OF-1519'],
  ['SEME', 'OVI9905', 'Ônibus Mercedes-Benz OF-1519'],
  ['SEME', 'SFT4C01', 'Ônibus Volkswagen Neobus 15.190'],
  ['SEME', 'SFT9J23', 'Micro-ônibus Marcopolo Volare V8L'],
  ['SEME', 'SFT9I98', 'Micro-ônibus Marcopolo Volare V8L'],
  ['SEME', 'SFT9J25', 'Micro-ônibus Marcopolo Volare V8L'],
  ['SEME', 'ODR3961', 'Micro-ônibus Marcopolo Volare V8L'],
  ['SEME', 'MSH2811', 'Furgão Iveco'],
  ['SEME', 'FUM7G56', 'Van Mercedes-Benz S312'],
  ['SEME', 'SGI2A50', 'Caminhonete Chevrolet S10'],
  ['SEME', 'SGA5A01', 'Veículo Chevrolet Onix Plus'],
  ['SEME', 'SGA5A02', 'Veículo Chevrolet Onix Plus'],
  ['ESPORTE', 'EQP0010-ESP', 'Trator cortador (identificação original EQP0010)'],
  ['ESPORTE', 'EQP0011', 'Trator cortador'],
  ['ESPORTE', 'EQP0012', 'Trator cortador'],
  ['ESPORTE', 'ODM2H01', 'Caminhonete Toyota Hilux 4x4'],
  ['PLANEJAMENTO', 'SGI4I81', 'Veículo Fiat Mobi'],
  ['SEMAD', 'SGL6B18', 'Veículo Chevrolet Onix Plus'],
  ['INFRA_RURAL', 'EQP0025', 'Escavadeira hidráulica XCMG'],
  ['INFRA_RURAL', 'EQP0032', 'Pá carregadeira XCMG'],
  ['INFRA_RURAL', 'SEM9000', 'Motoniveladora Caterpillar SEM 919'],
  ['INFRA_RURAL', 'EQP0030', 'Motoniveladora XCMG GR1803BR'],
  ['INFRA_RURAL', 'EQP0020', 'Motoniveladora New Holland RG140.B'],
  ['INFRA_RURAL', 'EQP0003', 'Motoniveladora Case 845B'],
  ['INFRA_RURAL', 'EQP0008', 'Pá carregadeira New Holland W130'],
  ['INFRA_RURAL', 'EQP0009', 'Pá carregadeira New Holland W130'],
  ['INFRA_RURAL', 'EQP0010-INFRA', 'Rolo compactador XCMG (identificação original EQP0010)'],
  ['INFRA_RURAL', 'SFR4A91', 'Motoniveladora XCMG GR1803BR'],
  ['INFRA_RURAL', 'EQP0C01', 'Motoniveladora Volvo G930'],
  ['INFRA_RURAL', 'SGH4H53', 'Caminhão Volvo VM270'],
  ['INFRA_RURAL', 'SGF8E05', 'Caminhão Foton Aumark'],
  ['INFRA_RURAL', 'SFU2B97', 'Caminhão Iveco Tector 24-280'],
  ['INFRA_RURAL', 'OVL0530', 'Caminhão Mercedes-Benz Atron 2729K'],
  ['INFRA_RURAL', 'PPM0088', 'Caminhão Volkswagen 13.190'],
  ['INFRA_RURAL', 'PPM0090', 'Caminhão Iveco Tector 150E31'],
  ['INFRA_RURAL', 'QRB8925', 'Caminhão Ford Cargo 2423B'],
  ['INFRA_RURAL', 'MRW4734', 'Caminhão Ford F11000'],
  ['INFRA_RURAL', 'SFQ2H00', 'Caminhão Mercedes-Benz Atego 1719/36'],
  ['INFRA_RURAL', 'MTX5931', 'Caminhonete Toyota Hilux'],
  ['INFRA_RURAL', 'MTV9D20', 'Caminhonete Toyota RAV4'],
  ['INFRA_RURAL', 'MTV9320', 'Caminhonete Toyota RAV4'],
  ['INFRA_RURAL', 'MTT1J18', 'Carro Volkswagen Voyage'],
  ['SEMCULT', 'ODO9888', 'Veículo Ford Fiesta'],
  ['SEMOSU', 'ODR2H01', 'Caminhonete Toyota Hilux'],
  ['SEMAS', 'SFZ3F94', 'Van Mercedes-Benz (SEMADES recurso próprio)'],
  ['SEMAS', 'SGH4E45', 'Veículo Chevrolet Onix Plus (CREAS)'],
  ['REVIVER', 'QRI5D72', 'Veículo Renault Sandero'],
  ['REVIVER', 'PPA7G15', 'Veículo Fiat Strada'],
  ['REVIVER', 'MSI3G37', 'Veículo Chevrolet Corsa'],
  ['SEMAS', 'SGM6H21', 'Veículo Fiat Strada (CRAS)'],
  ['SEMAS', 'SGO4G39', 'Veículo Fiat Strada (CRAS)'],
  ['SEMAS', 'SGL6B30', 'Veículo Chevrolet Onix Plus (CRAS)'],
  ['SEMAS', 'RQN5D54', 'Veículo Fiat Strada (CadÚnico)'],
  ['SEMAS', 'SGL6B39', 'Veículo Chevrolet Spin (CadÚnico)'],
  ['SEMAS', 'PPV0998', 'Veículo Chevrolet Spin (SEMADES recurso estadual)'],
  ['GABINETE', 'RQS9F70', 'Veículo Chevrolet Tracker (Prefeito)'],
  ['GABINETE', 'SGA9F78', 'Veículo Ford Ranger (Defesa Civil)'],
  ['SEMAG', 'SFQ9G42', 'Retroescavadeira XCMG'],
  ['SEMAG', 'EQP0016', 'Retroescavadeira JCB 3CX'],
  ['SEMAG', 'EQP0015', 'Retroescavadeira XCMG XE150BR'],
  ['SEMAG', 'EQP0023', 'Retroescavadeira Caterpillar'],
  ['SEMAG', 'TOE2I23', 'Retroescavadeira JCB 3CX'],
  ['SEMAG', 'EQP0024', 'Pá carregadeira Ensign'],
  ['SEMAG', 'EQP0014', 'Trator New Holland TT.4.75'],
  ['SEMAG', 'EQP0013', 'Trator New Holland TT.4.75'],
  ['SEMAG', 'SGD2D29', 'Caminhão Foton Aumark'],
  ['SEMAG', 'SGL7G89', 'Caminhão Mercedes-Benz Accelo'],
  ['SEMAG', 'ODT7C45', 'Caminhonete Ford Ranger'],
  ['SEMAG', 'SFZ5C85', 'Veículo Volkswagen Saveiro'],
  ['SEMAG', 'SGM6H28', 'Veículo Fiat Strada'],
  ['SEMAG', 'QRL3I07', 'Veículo Volkswagen Gol'],
  ['SEMAG', 'SGB9G46', 'Veículo Fiat Strada'],
  ['SEMAG', 'MSN5039', 'Veículo Volkswagen Gol'],
  ['SEMLIP', 'SGA3F39', 'Retroescavadeira XCMG XE150BR'],
  ['SEMLIP', 'MRT4C61', 'Caminhão Volkswagen 13.180'],
  ['SEMLIP', 'RBE3I41', 'Caminhão Mercedes-Benz Accelo 817'],
  ['SEMLIP', 'PPM0089', 'Caminhão Iveco Tector 150E21'],
  ['SEMLIP', 'PPM0087', 'Caminhão Volkswagen 13.190 (poliguindaste)'],
  ['SEMLIP', 'QRO4E10', 'Caminhão Volkswagen Constellation 14.190'],
  ['SEMLIP', 'SGB0D79', 'Caminhão Iveco Tector 15-210 (pipa)'],
  ['SEMLIP', 'SGB3H39', 'Caminhão Iveco Tector 15-210 (pipa)'],
  ['SEMLIP', 'RBH1J72', 'Caminhão Volkswagen coletor de lixo'],
  ['SEMLIP', 'ODR4G60', 'Kombi Volkswagen'],
  ['SEMLIP', 'S/PLACA', 'Veículo Ford sem placa'],
  ['SEMLIP', 'MOT0001', 'Motosserra'],
  ['SEMLIP', 'MOT0002', 'Motosserra'],
  ['SEMLIP', 'ROC0001', 'Roçadeira'],
  ['SEMLIP', 'ROC0002', 'Roçadeira'],
  ['SEMLIP', 'ROC0003', 'Roçadeira'],
] as const;
